# Generated by Django 5.0.1 on 2024-11-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_private_key_user_public_key_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
