name: My-Facebook-project
services:

  backend:
    build:
      context: ./facebook
      dockerfile: Dockerfile
    command: python -m daphne -b 0.0.0.0 -p 8000 facebook.asgi:application
    volumes:
    - ./facebook:/facebook 
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=facebook.settings
      - DEBUG=True

    depends_on:
      - redis
      - database
    
    
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/front-end/src
    depends_on:
      - backend

  redis:
    image: redis:alpine


  

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:


