# Generated by Django 5.0.1 on 2024-09-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting_blogs', '0003_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='followed_user',
        ),
    ]
