# Generated by Django 5.0.1 on 2025-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_blogs', '0007_story_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
