# Generated by Django 5.0.1 on 2025-02-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_blogs', '0008_alter_blogs_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='files/'),
        ),
    ]
