# Generated by Django 5.0.1 on 2024-10-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_messagereadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='is_read',
        ),
    ]
