# Generated by Django 5.0.1 on 2024-10-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_remove_messages_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
