# Generated by Django 5.0.1 on 2025-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0008_alter_messages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
